import cv2
import numpy as np

ARUCO_DICT_CONFIG = cv2.aruco.DICT_4X4_50

FRAME_DIMENSIONS = (640, 360)
WIDTH_OF_IMAGE = FRAME_DIMENSIONS[0]
HEIGHT_OF_IMAGE = FRAME_DIMENSIONS[1]
centre_of_frame = (int(FRAME_DIMENSIONS[0]/2),int(FRAME_DIMENSIONS[1]/2))


ARUCO_MARKER_SIZE = 0.0355

# percentage of frame for black line to be sought
LINE_SEEKING_PORTION = 60

# margins of error for marker alignment
MARGIN_OF_CENTER_MISALIGNMENT = 30
MARGIN_OF_DISTANCE = 1
MARGIN_OF_ANGLE = 2

DISTANCE_FROM_MARKER = 15

SPEED_STRAFE = 16
SPEED_ROLL = 14
SPEED_DRIVE = 10
SPEED_SPIN = 12


KALMAN_PROCESS_COEF = 0.0001
KALMAN_MEASUREMENT_COEF = 10
KALMAN_ERROR_COEF = 1



