import cv2
import numpy as np

ARUCO_DICT_CONFIG = cv2.aruco.DICT_4X4_50

FRAME_DIMENSIONS = (640, 360)
WIDTH_OF_IMAGE = FRAME_DIMENSIONS[0]
HEIGHT_OF_IMAGE = FRAME_DIMENSIONS[1]

ARUCO_MARKER_SIZE = 0.0355

#percentage of frame for black line to be sought
LINE_SEEKING_PORTION = 60

MARGIN_OF_CENTER = 30

MARGIN_OF_DISTANCE = 15

MARGIN_OF_ANGLE = 3

SPEED_SLIDE = 17
SPEED_ROLL = 17
SPEED_DRIVE = 10
SPEED_SPIN = 12




