import cv2
import numpy as np

ARUCO_DICT_CONFIG = cv2.aruco.DICT_4X4_50

FRAME_DIMENSIONS = (640, 360)
WIDTH_OF_IMAGE = FRAME_DIMENSIONS[0]
HEIGHT_OF_IMAGE = FRAME_DIMENSIONS[1]
centre_of_frame = (int(FRAME_DIMENSIONS[0]/2),int(FRAME_DIMENSIONS[1]/2))

ARUCO_MARKER_SIZE = 0.0355

# percentage of frame for black line to be sought
LINE_SEEKING_PORTION = 30

# margins of error for marker alignment
MARGIN_OF_CENTER_MISALIGNMENT = 30
MARGIN_OF_DISTANCE = 3
MARGIN_OF_ANGLE = 2

DISTANCE_FROM_MARKER = 15

SPEED_STRAFE = 17
SPEED_ROLL = 14
SPEED_DRIVE = 10
SPEED_SPIN = 13
MAX_SPEED = 25

SPEED_COEF = 0.3
OFFSET_COEF = 0.2
ANGLE_COEF = 0.3

KALMAN_PROCESS_COEF = 1e-6               #Q
KALMAN_MEASUREMENT_COEF = 5e-6          #R
KALMAN_ERROR_COEF = 1
